# Generated by Django 4.1.3 on 2022-11-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='catch_quantity',
            field=models.FloatField(default=1),
        ),
    ]
