# Generated by Django 4.1.3 on 2022-11-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_ware_catch_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='catch_quantity',
            field=models.FloatField(db_column='catch_qty', default=1, verbose_name='Минимальный порог'),
        ),
    ]
