# Generated by Django 4.1.3 on 2022-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='icon',
            field=models.CharField(default='bi bi-bag', max_length=64, verbose_name='Иконка элемента'),
        ),
    ]
