# Generated by Django 4.1.4 on 2022-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_department_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='short_name',
            field=models.CharField(db_column='s_name', max_length=24, verbose_name='Название товара (сокращенное)'),
        ),
    ]
