# Generated by Django 4.1.4 on 2022-12-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_ware_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='short_name',
            field=models.CharField(db_column='s_name', max_length=80, verbose_name='Название товара (сокращенное)'),
        ),
    ]
