# Generated by Django 4.1.3 on 2022-11-14 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPrinterDevice',
            fields=[
                ('guid', models.CharField(db_column='guid', default=uuid.UUID('c35ab23f-2d4b-401d-a6d9-66ce03066910'), max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства')),
                ('name', models.CharField(default='Нет названия', max_length=128, verbose_name='Наименование устройства')),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP адрес устройства')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'db_table': 'printer',
            },
        ),
        migrations.CreateModel(
            name='ModelCash',
            fields=[
                ('guid', models.CharField(db_column='guid', default=uuid.UUID('b4b34de9-1cdb-4fa1-a18e-b8e6ababa2c2'), max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства')),
                ('name', models.CharField(default='Нет названия', max_length=128, verbose_name='Наименование устройства')),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP адрес устройства')),
                ('pg_login', models.CharField(max_length=64, verbose_name='Логин SQL')),
                ('pg_password', models.CharField(max_length=64, verbose_name='Пароль SQL')),
                ('pg_db_name', models.CharField(max_length=64, verbose_name='Наименование БД')),
                ('request_interval', models.IntegerField(default=2000, verbose_name='Интервал опроса кассы, м/сек')),
                ('cash_printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_devices.modelprinterdevice', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'db_table': 'cash',
            },
        ),
    ]
