# Generated by Django 4.1.3 on 2022-11-16 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('guid', models.CharField(db_column='guid', default=uuid.UUID('de602b4d-c75f-4ba0-adc9-60b8896562e8'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства')),
                ('cash_number', models.IntegerField(db_column='cash_id', default=1, unique=True, verbose_name='Номер кассы')),
                ('name', models.CharField(db_column='name', default='Нет названия', max_length=128, verbose_name='Наименование устройства')),
                ('ip_address', models.GenericIPAddressField(db_column='ip', default='127.0.0.1', verbose_name='IP адрес кассы')),
                ('pg_login', models.CharField(db_column='sql_login', max_length=64, verbose_name='Логин SQL')),
                ('pg_password', models.CharField(db_column='sql_passw', max_length=64, verbose_name='Пароль SQL')),
                ('pg_db_name', models.CharField(db_column='sql_db', max_length=64, verbose_name='Наименование БД')),
                ('request_interval', models.IntegerField(db_column='request_interval', default=2000, verbose_name='Интервал опроса кассы, м/сек')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'db_table': 'cash',
            },
        ),
        migrations.CreateModel(
            name='ImportedChecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_id', models.IntegerField(db_column='cash_id', default=1, verbose_name='Номер кассы')),
                ('check_id', models.IntegerField(db_column='check_id', default=1, verbose_name='Номер чека')),
                ('check_date', models.DateField(auto_now_add=True, db_column='check_dts', verbose_name='Дата чека')),
                ('ware_code', models.CharField(db_column='code', max_length=16, unique=True, verbose_name='Локальный код товара')),
                ('ware_count', models.IntegerField(db_column='cnt', default=1, verbose_name='Количество')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, db_column='dts', verbose_name='Дата создания')),
                ('processed', models.BooleanField(db_column='processed', default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'db_table': 'import_checks',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('guid', models.CharField(db_column='guid', default=uuid.UUID('ea058b0d-8563-43c2-a20f-a5fd1c599e90'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства')),
                ('name', models.CharField(default='Нет названия', max_length=128, verbose_name='Наименование устройства')),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP адрес устройства')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'db_table': 'printer',
            },
        ),
        migrations.AddConstraint(
            model_name='importedchecks',
            constraint=models.UniqueConstraint(fields=('cash_id', 'check_id', 'check_date'), name='app_devices_importedchecks_unique'),
        ),
        migrations.AddField(
            model_name='cash',
            name='printer_guid',
            field=models.ForeignKey(db_column='printer_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_devices.printer', verbose_name='Принтер'),
        ),
    ]
