# Generated by Django 4.1.3 on 2022-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='pg_db_name',
            field=models.CharField(db_column='sql_db', default='cash', max_length=64, verbose_name='Наименование БД'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='pg_login',
            field=models.CharField(db_column='sql_login', default='postgres', max_length=64, verbose_name='Логин SQL'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='pg_password',
            field=models.CharField(db_column='sql_passw', default='postgres', max_length=64, verbose_name='Пароль SQL'),
        ),
    ]
