# Generated by Django 4.1.3 on 2022-11-16 10:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.UUID('2b7ca699-41dc-42ed-8bc7-73a372b2a512'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства'),
        ),
        migrations.AlterField(
            model_name='importedchecks',
            name='check_date',
            field=models.DateField(db_column='check_dts', default=django.utils.timezone.now, verbose_name='Дата чека'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.UUID('060891e7-8207-479c-a90a-04d5bf96b94b'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства'),
        ),
    ]
