# Generated by Django 4.1.3 on 2022-11-15 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.UUID('c6ef2917-30b6-414f-8f29-364fa1422e49'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.UUID('fa4465da-b966-4c8b-a03d-d718c6ce1185'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства'),
        ),
    ]
