# Generated by Django 4.1.3 on 2022-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0002_alter_cash_pg_db_name_alter_cash_pg_login_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importedchecks',
            name='app_devices_importedchecks_unique',
        ),
        migrations.AddField(
            model_name='importedchecks',
            name='shift_id',
            field=models.IntegerField(db_column='shift_id', default=1, verbose_name='Номер смены'),
        ),
        migrations.AddConstraint(
            model_name='importedchecks',
            constraint=models.UniqueConstraint(fields=('cash_guid', 'check_id', 'shift_id', 'check_date'), name='app_devices_importedchecks_unique'),
        ),
    ]
