# Generated by Django 4.1.3 on 2022-11-15 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0002_alter_cash_guid_alter_printer_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='cash_number',
            field=models.IntegerField(db_column='cash_id', default=1, unique=True, verbose_name='Номер кассы'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.UUID('b7838836-749f-4c34-8177-8113e92dab58'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.UUID('18083c75-3c0e-4041-9e7b-22a8c595f1b0'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства'),
        ),
    ]
