# Generated by Django 4.1.3 on 2022-11-15 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0003_cash_cash_number_alter_cash_guid_alter_printer_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedChecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_id', models.IntegerField(db_column='cash_id', default=1, verbose_name='Номер кассы')),
                ('check_id', models.IntegerField(db_column='check_id', default=1, verbose_name='Номер чека')),
                ('check_date', models.DateField(auto_now_add=True, db_column='check_dts', verbose_name='Дата чека')),
                ('ware_code', models.CharField(db_column='code', max_length=16, unique=True, verbose_name='Локальный код товара')),
                ('ware_count', models.IntegerField(db_column='cnt', default=1, verbose_name='Количество')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, db_column='dts', verbose_name='Дата создания')),
                ('processed', models.BooleanField(db_column='processed', default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'db_table': 'import_checks',
            },
        ),
        migrations.AlterField(
            model_name='cash',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.UUID('eb736d0a-a5d9-4554-8d68-9fa8d0af6910'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='guid',
            field=models.CharField(db_column='guid', default=uuid.UUID('ff823aae-2ffb-4478-8e41-bdc5404b5da4'), editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='ИД устройства'),
        ),
        migrations.AddConstraint(
            model_name='importedchecks',
            constraint=models.UniqueConstraint(fields=('cash_id', 'check_id', 'check_date'), name='app_devices_importedchecks_unique'),
        ),
    ]
